services:
  mongo:
    container_name: todo-list-mongo
    image: mongo
    ports:
      - 27017:27017
  redis:
    container_name: todo-list-redis
    image: redis:alpine
    ports:
      - 6379:6379
